- inji-web/src/Router.js
- inji-web/src/pages/Home/IssuerList.js
- inji-web/src/pages/Home/SearchIssuers.js
- inji-web/src/pages/IssuerPage/Header.js
- inji-web/src/pages/IssuerPage/index.js
Using issuer display name for display purposes on the UI
> Update issuer display name

- inji-web/Dockerfile
Signed-off-by: Shiva <shivakumar@beehyv.com>
> Add Labels to Docker image

- inji-web/src/components/Home/IssuerList.js
- inji-web/src/components/Home/SearchIssuers.js
- inji-web/src/components/Issuers/Header.js
- inji-web/src/pages/Home/HomePage.js
Issues part of this PR : 
[INJIWEB-181](https://github.com/mosip/inji-web/commit/d55fd13ae964b8742e1524742b1ec2ed876c19ce) - fixed the literals for error handling.
[INJIWEB-56 & INJIWEB-57](https://github.com/mosip/inji-web/commit/5c21186db0390f49a92555874cbcabd4b512a074) -  remove the default option population for credential type screen
[INJIWEB-181]: https://mosip.atlassian.net/browse/INJIWEB-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> INJIWEB release fixes

- inji-web/src/__tests__/components/Credentials/Credentials.test.tsx
- inji-web/src/__tests__/components/PageTemplate/Header.test.tsx
- inji-web/src/components/Common/LanguageSelector.tsx
- inji-web/src/components/Common/NavBar.tsx
- inji-web/src/components/Credentials/CredentialList.tsx
- inji-web/src/components/Credentials/SearchCredential.tsx
- inji-web/src/components/Help/HelpAccordionItem.tsx
- inji-web/src/components/Issuers/Issuer.tsx
- inji-web/src/components/Issuers/IssuersList.tsx
- inji-web/src/components/Issuers/SearchIssuer.tsx
- inji-web/src/components/PageTemplate/Header.tsx
- inji-web/src/hooks/useFetch.tsx
- inji-web/src/pages/CredentialsPage.tsx
- inji-web/src/pages/HomePage.tsx
- inji-web/src/redux/reducers/commonReducer.ts
- inji-web/src/redux/reducers/credentialsReducer.ts
- inji-web/src/redux/reducers/issuersReducer.ts
- inji-web/src/types/redux.d.ts
- inji-web/src/utils/api.ts
- inji-web/src/utils/i18n.ts
**Fixes Done as a part of this PR** 
1. [INJIWEB-464](https://mosip.atlassian.net/browse/INJIWEB-464) - INJIWEB: Inappropriate error message when "/" entered in the search box
2. [INJIWEB-466](https://mosip.atlassian.net/browse/INJIWEB-466) - INJIWEB: Search result is not properly getting refreshed after clearing entire text from it(intermittent)
3. [INJIWEB-571](https://mosip.atlassian.net/browse/INJIWEB-571) - Injiweb: In the help document, it's not possible to minimize of all the fields
4. [INJIWEB-564](https://mosip.atlassian.net/browse/INJIWEB-564) - INJIWEB: language dropdown is active until selecting a different one 
[INJIWEB-464]: https://mosip.atlassian.net/browse/INJIWEB-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> INJIWEB : UI Fixes and use wellknown to refer credential types

- inji-web-test/browserstack.yml
- inji-web-test/pom.xml
- inji-web-test/src/main/java/base/BasePage.java
- inji-web-test/src/main/java/pages/HomePage.java
- inji-web-test/src/main/java/pages/MosipCredentials.java
- inji-web-test/src/main/java/pages/PDFContentVerification.java
- inji-web-test/src/main/java/pages/SunbirdCredentials.java
- inji-web-test/src/test/java/runnerfiles/Runner.java
- inji-web-test/src/test/java/stepdefinitions/StepDef.java
- inji-web-test/src/test/java/utils/BaseTest.java
- inji-web-test/src/test/resources/featurefiles/downloadMosipCredentials.feature
- inji-web-test/src/test/resources/featurefiles/helppage.feature
- inji-web-test/src/test/resources/featurefiles/homepage.feature
- inji-web-test/src/test/resources/featurefiles/multilanguage.feature
- inji-web-test/src/test/resources/featurefiles/subirdVc.feature
- inji-web-test/src/test/resources/featurefiles/sunbirdVc.feature
added new testcases and intergration of browserStack  MOSIP-32808
> added new testcases and intergration of browserStack  MOSIP-32808

- .github/workflows/chart-lint-publish.yml
> Revert "[MOSIP-33402] Updated chart-lint-publish.yml"

- .github/workflows/browserstack-web.yml
- inji-web-test/pom.xml
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JAVA-ORGSELENIUMHQSELENIUM-6062318
- https://snyk.io/vuln/SNYK-JAVA-ORGYAML-3152153
- https://snyk.io/vuln/SNYK-JAVA-ORGJSOUP-1567345
- https://snyk.io/vuln/SNYK-JAVA-ORGYAML-2806360
- https://snyk.io/vuln/SNYK-JAVA-ORGYAML-6056527
- https://snyk.io/vuln/SNYK-JAVA-IONETTY-6483812
- https://snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327
- https://snyk.io/vuln/SNYK-JAVA-IONETTY-5725787
- https://snyk.io/vuln/SNYK-JAVA-ORGYAML-3016891
- https://snyk.io/vuln/SNYK-JAVA-ORGYAML-3016888
- https://snyk.io/vuln/SNYK-JAVA-IONETTY-2812456
- https://snyk.io/vuln/SNYK-JAVA-ORGJSOUP-2989728
- https://snyk.io/vuln/SNYK-JAVA-ORGYAML-3016889
- https://snyk.io/vuln/SNYK-JAVA-ORGYAML-3113851
- …
> snyk fix: inji-web-test/pom.xml to reduce vulnerabilities

- inji-web-test/src/main/java/pages/SunbirdCredentials.java
- inji-web-test/src/test/java/stepdefinitions/StepDef.java
MOSIP-35488  fixed inji ui automation
> MOSIP-35488  fixed inji ui automation

- inji-web-test/src/test/java/stepdefinitions/StepDef.java
- inji-web-test/src/test/resources/featurefiles/subirdVc.feature
> INJIWEB-746 fix injeweb Ui

- inji-web-test/src/main/java/pages/SunbirdCredentials.java
- inji-web-test/src/test/java/stepdefinitions/StepDef.java
- inji-web-test/src/test/resources/featurefiles/subirdVc.feature
>  sync the code Release 0.10.x

- inji-web-proxy/.env
- inji-web-proxy/.gitignore
- inji-web-proxy/Dockerfile
- inji-web-proxy/README.md
- inji-web-proxy/package.json
- inji-web-proxy/proxy_server.js
- inji-web/.env
- inji-web/src/utils/api.ts
[INJICERT-567] demo changes
[INJICERT-567]: https://mosip.atlassian.net/browse/INJICERT-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [INJICERT-567]

- inji-web-test/src/main/java/pages/HomePage.java
- inji-web-test/src/main/java/pages/SunbirdCredentials.java
- inji-web-test/src/test/java/stepdefinitions/StepDef.java
- inji-web-test/src/test/java/stepdefinitions/StepDefMosipCredentials.java
- inji-web-test/src/test/java/stepdefinitions/StepDefSunbirdCredentials.java
- inji-web-test/src/test/java/utils/BaseTest.java
- inji-web-test/src/test/java/utils/GlobelConstants.java
- inji-web-test/src/test/resources/featurefiles/downloadMosipCredentials.feature
- inji-web-test/src/test/resources/featurefiles/downloadSunbirdCredentials.feature
- inji-web-test/src/test/resources/featurefiles/homePage.feature
- inji-web-test/src/test/resources/featurefiles/multiLanguage.feature
sync  automation code with develop
>  sync  automation code with develop

- docker-compose/config/mimoto-issuers-config.json
- inji-web/src/__tests__/pages/RedirectionPage.test.tsx
- inji-web/src/__tests__/utils/api.test.tsx
- inji-web/src/components/Issuers/Issuer.tsx
- inji-web/src/pages/RedirectionPage.tsx
- inji-web/src/test-utils/mockObjects.tsx
- inji-web/src/types/data.d.ts
Updating attribute name from **credential_issuer** to **issuer_id** to align with wellknown **credential_issuer**
> [INJIMOB-2452]: Updating attribute name from credential_issuer to issuer_id

- inji-web-test/src/main/java/pages/MosipCredentials.java
- inji-web-test/src/main/java/pages/SunbirdCredentials.java
- inji-web-test/src/test/java/stepdefinitions/StepDefMosipCredentials.java
- inji-web-test/src/test/java/stepdefinitions/StepDefSunbirdCredentials.java
INJIWEB-1416  retry logic for download the sunbird vc
> INJIWEB-1416 retry logic for download the sunbird vc

- inji-web-test/src/test/java/utils/BaseTest.java
- inji-web-test/src/test/java/utils/GlobelConstants.java
- inji-web-test/src/test/resources/featurefiles/downloadMosipCredentials.feature
- inji-web-test/src/test/resources/featurefiles/downloadSunbirdCredentials.feature
MOSIP-39650 updated the assert for multilanguage testcase
-updated new uin and vid
> MOSIP-39650 updated the assert for multilanguage testcase

- inji-web-test/src/main/java/pages/HomePage.java
- inji-web-test/src/test/java/stepdefinitions/StepDef.java
- inji-web-test/src/test/java/utils/GlobelConstants.java
- inji-web-test/src/test/resources/featurefiles/multiLanguage.feature
Include Portgual lang support in inji web
> MOSIP-39057 Include Portgual lang support in inji web

- inji-web-test/pom.xml
MOSIP-39650 - Update the release version in POM
updated version - 0.11.1-SNAPSHOT
> MOSIP-39650 - Update the release version in POM

- ui-test/src/test/java/utils/GlobelConstants.java
INJIWEB-1492 Update GlobelConstants.java
> INJIWEB-1492 Update GlobelConstants.java

- ui-test/src/main/java/pages/MosipCredentials.java
- ui-test/src/test/java/stepdefinitions/StepDef.java
- ui-test/src/test/java/utils/BaseTest.java
- ui-test/src/test/resources/config.properties
- ui-test/src/test/resources/featurefiles/downloadMosipCredentials.feature
- ui-test/src/test/resources/featurefiles/downloadSunbirdCredentials.feature
MOSIP-40795 Added the config property to read the issuer element text
> MOSIP-40795 Added the config property to read the issuer element text

- inji-web/src/__tests__/components/PageTemplate/Header.test.tsx
- inji-web/src/__tests__/components/PageTemplate/__snapshots__/Header.test.tsx.snap
- inji-web/src/components/PageTemplate/Header.tsx
- inji-web/src/pages/HomePage.tsx
- inji-web/src/pages/users/PinPage.tsx
- inji-web/src/pages/users/login/Login.tsx
- inji-web/src/pages/users/login/LoginSessionStatusChecker.tsx
- Updated the responses for all the endpoints in the login flow as backend will send the response without any wrapper
- Fixed failing test cases in header file
- Updated the logic in LogicSessionStatusChecker component to listen to the changes in the local storage for displayName key and call the session and user endpoints accordingly.
> [Injiweb 1379] login flow enhancements

- inji-web/src/Router.tsx
- inji-web/src/components/PageTemplate/Header.tsx
- inji-web/src/pages/RedirectionPage.tsx
- inji-web/src/pages/users/PinPage.tsx
- inji-web/src/pages/users/login/WalletCredentialsPage.tsx
- inji-web/src/types/data.d.ts
- inji-web/src/utils/api.ts
- Made changes to use the new endpoints of mimoto to download and store a credential and to fetch all the credentials in the login flow
- Added a Mock Page in the UI to show all the downloaded credentials of a specific wallet
> [Injiweb 1418] make changes to use the mimoto endpoints to download and fetch the credentials in the login flow

- ui-test/Dockerfile
- ui-test/pom.xml
- ui-test/src/main/java/runnerfiles/Runner.java
INJIWEB-1539 updated the apitest-commons version
> INJIWEB-1539 updated the apitest-commons version

- ui-test/src/main/java/pages/HomePage.java
- ui-test/src/main/java/stepdefinitions/StepDef.java
- ui-test/src/main/java/stepdefinitions/StepDefSunbirdCredentials.java
- ui-test/src/test/resources/featurefiles/downloadMosipCredentials.feature
- ui-test/src/test/resources/featurefiles/downloadSunbirdCredentials.feature
- ui-test/src/test/resources/featurefiles/homePage.feature
- ui-test/src/test/resources/featurefiles/multiLanguage.feature
injiweb update automation scripts for Guest user login
> INJIWEB-1566:injiweb update automation scripts for Guest user login

- inji-web/package-lock.json
- inji-web/package.json
- inji-web/src/__tests__/components/Common/Preview/PDFViewer.test.tsx
- inji-web/src/__tests__/components/Common/Preview/__snapshots__/PDFViewer.test.tsx.snap
- inji-web/src/__tests__/components/VC/VCCardView.test.tsx
- inji-web/src/__tests__/components/VC/__snapshots__/VCCardView.test.tsx.snap
- inji-web/src/__tests__/pages/User/StoredCardsPage.test.tsx
- inji-web/src/components/Common/toast/AppToaster.tsx
- inji-web/src/components/Preview/PDFViewer.tsx
- inji-web/src/components/VC/VCCardView.tsx
- inji-web/src/components/VC/VCDetailView.tsx
- inji-web/src/setupTests.ts
- inji-web/src/utils/constants.ts
Changes
- Toaster time updated to 3 seconds
- PDF preview is using react-pdf library which is comparatively having more stars & released recently compared with react-pdf-viewer
> [INJIWEB-1519] fix pdf preview showing duplicate content

- ui-test/src/main/java/stepdefinitions/StepDefOIDCLogin.java
- ui-test/src/main/java/utils/BaseTest.java
- ui-test/src/main/java/utils/HttpUtils.java
- ui-test/src/test/resources/config.properties
Updated scripts to consider Issuer search text from env
> Updated scripts to consider Issuer search text from env

- ui-test/src/main/java/utils/BaseTest.java
Updated pdf name for Mosip credentials
> Updated pdf name for Mosip credentials
